AWSTemplateFormatVersion: '2010-09-09'
Description: Env-based parameters store using Custom Resource

Parameters:
  environment:
    Type: String
    AllowedValues:
      - qa

  SecureStringValue1:
    Type: String
    NoEcho: true

  SecureStringValue2:
    Type: String
    NoEcho: true

Mappings:
  EnvMap:
    qa:
      StringValue1: "qa-string-value-1"
      StringValue2: "qa-string-value-2"

Resources:

  SecureParam1:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/SECURESTRING/PARAM1
      Type: SecureString
      Value: !Ref SecureStringValue1

  SecureParam2:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/SECURESTRING/PARAM2
      Type: SecureString
      Value: !Ref SecureStringValue2

  StringParam1:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/STRING/PARAM1
      Type: String
      Value: !FindInMap
        - EnvMap
        - !Ref environment
        - StringValue1

  StringParam2:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/STRING/PARAM2
      Type: String
      Value: !FindInMap
        - EnvMap
        - !Ref environment
        - StringValue2

Outputs:
  Status:
    Value: SecureString and String parameters created successfully