AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Parameter Store - Common and Environment-specific SSM 
  parameters

Parameters:
  environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
    Default: dev

  Scope:
    Type: String
    AllowedValues:
      - common
      - env
    Default: env
    Description: "common = deploy only common params, env = deploy only env-specific
      params"

  Param18HRPORTALROLESValue:
    Type: String
    NoEcho: true
    Default: "none"

Conditions:
  IsCommonScope:
    Fn::Equals:
      - Ref: Scope
      - common
  IsEnvScope:
    Fn::Equals:
      - Ref: Scope
      - env

  DeployParam18HRPORTALROLES:
    Fn::And:
      - Condition: IsEnvScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param18HRPORTALROLESValue
              - none

Resources:

  Param18HRPORTALROLES:
    Type: Custom::SecureSSMParameter
    Condition: DeployParam18HRPORTALROLES
    Properties:
      ServiceToken: 
        arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: HR_PORTAL_ROLES
      Type: SecureString
      Value: Param18HRPORTALROLESValue

Outputs:
  Status:
    Value: !Sub "Parameters created successfully for scope: ${Scope}"
  Environment:
    Value: !Ref environment
    Condition: IsEnvScope
  ParametersCreated:
    Value: "Parameters processed successfully"