AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Parameter Store - Common and Environment-specific SSM 
  parameters

Parameters:
  environment:
    Type: String
    AllowedValues:
      - dev
      - qa
      - stage
      - prod
    Default: dev

  Scope:
    Type: String
    AllowedValues:
      - common
      - env
    Default: env
    Description: "common = deploy only common params, env = deploy only env-specific
      params"

  Param18HRPORTALROLESValue:
    Type: String
    NoEcho: true
    Default: "none"
  
  Param22OPERATIONSPORTALROLESValue:
    Type: String
    NoEcho: true
    Default: "none"

  Param29SALESPORTALROLESValue:
    Type: String
    NoEcho: true
    Default: "none"
    
  Param36GUNNERNONSERVICESTATEValue:
    Type: String
    NoEcho: true
    Default: "none"
  
  Param3DOCUSIGNACCOUNTIDValue:
    Type: String
    NoEcho: true
    Default: "none"
  
  Param1COGNITOCLIENTIDValue:
    Type: String
    NoEcho: true
    Default: "none"

  Param46REDISREADCONNECTIONValue:
    Type: String
    NoEcho: true
    Default: "none"

Conditions:
  IsCommonScope:
    Fn::Equals:
      - Ref: Scope
      - common
  IsEnvScope:
    Fn::Equals:
      - Ref: Scope
      - env

  DeployParam18HRPORTALROLES:
    Fn::And:
      - Condition: IsCommonScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param18HRPORTALROLESValue
              - none

  DeployParam22OPERATIONSPORTALROLES:
    Fn::And:
      - Condition: IsCommonScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param22OPERATIONSPORTALROLESValue
              - none

  DeployParam29SALESPORTALROLES:
    Fn::And:
      - Condition: IsCommonScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param29SALESPORTALROLESValue
              - none

  DeployParam36GUNNERNONSERVICESTATE:
    Fn::And:
      - Condition: IsCommonScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param36GUNNERNONSERVICESTATEValue
              - none

  DeployParam3DOCUSIGNACCOUNTID:
    Fn::And:
      - Condition: IsCommonScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param3DOCUSIGNACCOUNTIDValue
              - none

  DeployParam1COGNITOCLIENTID:
    Fn::And:
      - Condition: IsEnvScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param1COGNITOCLIENTIDValue
              - none

  DeployParam46REDISREADCONNECTION:
    Fn::And:
      - Condition: IsEnvScope
      - Fn::Not:
          - Fn::Equals:
              - Ref: Param46REDISREADCONNECTIONValue
              - none

Resources:
  
  Param22OPERATIONSPORTALROLES:
    Type: AWS::SSM::Parameter
    Condition: DeployParam22OPERATIONSPORTALROLES
    Properties:
      Name: OPERATIONS_PORTAL_ROLES
      Type: String
      Value: !Ref Param22OPERATIONSPORTALROLESValue
  
  Param18HRPORTALROLES:
    Type: AWS::SSM::Parameter
    Condition: DeployParam18HRPORTALROLES
    Properties:
      Name: HR_PORTAL_ROLES
      Type: String
      Value: !Ref Param18HRPORTALROLESValue

  Param29SALESPORTALROLES:
    Type: AWS::SSM::Parameter
    Condition: DeployParam29SALESPORTALROLES
    Properties:
      Name: SALES_PORTAL_ROLES
      Type: String
      Value: !Ref Param29SALESPORTALROLESValue

  Param36GUNNERNONSERVICESTATE:
    Type: Custom::SecureSSMParameter
    Condition: DeployParam36GUNNERNONSERVICESTATE
    Properties:
      ServiceToken: 
        arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /GUNNER/NON_SERVICE_STATE
      Type: SecureString
      Value: !Ref Param36GUNNERNONSERVICESTATEValue

  Param3DOCUSIGNACCOUNTID:
    Type: Custom::SecureSSMParameter
    Condition: DeployParam3DOCUSIGNACCOUNTID
    Properties:
      ServiceToken: 
        arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /DOCUSIGN/ACCOUNT_ID
      Type: SecureString
      Value: !Ref Param3DOCUSIGNACCOUNTIDValue

  Param1COGNITOCLIENTID:
    Type: Custom::SecureSSMParameter
    Condition: DeployParam1COGNITOCLIENTID
    Properties:
      ServiceToken: 
        arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /COGNITO/CLIENT_ID
      Type: SecureString
      Value: !Ref Param1COGNITOCLIENTIDValue

  Param46REDISREADCONNECTION:
    Type: Custom::SecureSSMParameter
    Condition: DeployParam46REDISREADCONNECTION
    Properties:
      ServiceToken: 
        arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /REDIS/READ_CONNECTION
      Type: SecureString
      Value: !Ref Param46REDISREADCONNECTIONValue

Outputs:
  Status:
    Value: !Sub "Parameters created successfully for scope: ${Scope}"
  Environment:
    Value: !Ref environment
    Condition: IsEnvScope
  ParametersCreated:
    Value: "Parameters processed successfully"