AWSTemplateFormatVersion: '2010-09-09'
Description: SecureString + String test using Custom Resource (NO impact on existing params)

Parameters:
  SecureStringSmokeTest:
    Type: String
    NoEcho: true

  StringSmokeTest:
    Type: String
    Default: "dummy-string-smoke-test-value"

Resources:

  SmokeTestSecureParam:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/SECURESTRING/SMOKE_TEST
      Type: SecureString
      Value: !Ref SecureStringSmokeTest

  SmokeTestStringParam:
    Type: Custom::SecureSSMParameter
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /TEST/STRING/SMOKE_TEST
      Type: String
      Value: !Ref StringSmokeTest

Outputs:
  Status:
    Value: SecureString and String smoke tests deployed successfully
