AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SSM Parameter Store managed via SAM

Parameters:
  # =====================
  # Secure Parameters
  # =====================
  COGNITO_CLIENT_ID:
    Type: String
    NoEcho: true
  COGNITO_USER_POOL_ID:
    Type: String
    NoEcho: true
  EMAIL_FROM_EMAIL:
    Type: String
    NoEcho: true
  CONTRACT_PORTAL_HMAC_SECRET:
    Type: String
    NoEcho: true
  HUBSPOT_API_KEY:
    Type: String
    NoEcho: true
  DB_CONNECTION_STRING:
    Type: String
    NoEcho: true
  SMTP_DETAILS:
    Type: String
    NoEcho: true
  SNS_PROJECT:
    Type: String
    NoEcho: true
  SNS_PUSH_NOTIFICATION:
    Type: String
    NoEcho: true
  SNOWFLAKE_PASSWORD:
    Type: String
    NoEcho: true
  SNOWFLAKE_USERNAME:
    Type: String
    NoEcho: true
  SNOWFLAKE_WAREHOUSE:
    Type: String
    NoEcho: true

Resources:

  # =====================
  # COGNITO
  # =====================
  CognitoClientId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /COGNITO/CLIENT_ID
      Type: SecureString
      Value: !Ref COGNITO_CLIENT_ID

  CognitoUserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /COGNITO/USER_POOL_ID
      Type: SecureString
      Value: !Ref COGNITO_USER_POOL_ID

  # =====================
  # DOCUSIGN (STRING)
  # =====================
  DocusignAccountId:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /DOCUSIGN/ACCOUNT_ID
      Type: String
      Value: "2351e7ea-8e50-4625-a872-58f7ea89beb1"

  DocusignAuthDomain:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /DOCUSIGN/AUTH_DOMAIN
      Type: String
      Value: "account.docusign.com"

  DocusignBasePath:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /DOCUSIGN/BASE_PATH
      Type: String
      Value: "https://na4.docusign.net/restapi"

  DocusignIntegrationKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /DOCUSIGN/INTEGRATION_KEY
      Type: String
      Value: "6fccc78b-0b80-4eea-99d3-feb70b102ab8"

  # =====================
  # EMAIL
  # =====================
  FromEmail:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /EMAIL/FROM_EMAIL
      Type: SecureString
      Value: !Ref EMAIL_FROM_EMAIL

  # =====================
  # CONTRACT
  # =====================
  ContractPortalSecret:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CONTRACT_PORTAL_HMAC_SECRET
      Type: SecureString
      Value: !Ref CONTRACT_PORTAL_HMAC_SECRET

  ContractApiUrl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: CONTRACT_API_URL
      Type: String
      Value: "https://api-prod.gunnerroofing.com/project/send-contract?id="

  # =====================
  # HUBSPOT
  # =====================
  HubspotApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /HUBSPOT/API_KEY
      Type: SecureString
      Value: !Ref HUBSPOT_API_KEY

  # =====================
  # DATABASE
  # =====================
  DbConnection:
    Type: AWS::SSM::Parameter
    Properties:
      Name: DB_CONNECTION_STRING
      Type: SecureString
      Value: !Ref DB_CONNECTION_STRING

  # =====================
  # SMTP
  # =====================
  SmtpDetails:
    Type: AWS::SSM::Parameter
    Properties:
      Name: SMTP_DETAILS
      Type: SecureString
      Value: !Ref SMTP_DETAILS

  # =====================
  # SNS
  # =====================
  SnsProject:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SNS_TOPIC/PROJECT
      Type: SecureString
      Value: !Ref SNS_PROJECT

  SnsPush:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SNS_TOPIC/SNS_PUSH_NOTIFICATION
      Type: SecureString
      Value: !Ref SNS_PUSH_NOTIFICATION

  # =====================
  # SNOWFLAKE
  # =====================
  SnowflakeUsername:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SNOWFLAKE/USERNAME
      Type: SecureString
      Value: !Ref SNOWFLAKE_USERNAME

  SnowflakePassword:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SNOWFLAKE/PASSWORD
      Type: SecureString
      Value: !Ref SNOWFLAKE_PASSWORD

  SnowflakeWarehouse:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /SNOWFLAKE/WAREHOUSE
      Type: SecureString
      Value: !Ref SNOWFLAKE_WAREHOUSE

Outputs:
  Status:
    Value: Parameter Store deployment successful
