AWSTemplateFormatVersion: '2010-09-09'
Description: Parameter Store deployment Keys only

Resources:

  AppParameters:
    Type: Custom::SSMParameterKeys
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:123456789012:function:ssm-parameter-manager
      Parameters:
        - Name: /DUMMY/APP/ENV
          Type: String
          SecretName: DUMMY_APP_ENV

        - Name: /DUMMY/DB/PASSWORD
          Type: SecureString
          SecretName: DUMMY_DB_PASSWORD

Outputs:
  Status:
    Value: Parameters created successfully