AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Parameter Store - Common and Environment-specific SSM parameters
Parameters:
  environment:
    Type: String
    AllowedValues:
    - dev
    - qa
    - stage
    - prod
    Default: dev
  Scope:
    Type: String
    AllowedValues:
    - common
    - env
    Default: env
    Description: common = deploy only common params, env = deploy only env-specific
      params
  COGNITOCLIENTID-Value:
    Type: String
    NoEcho: true
Conditions:
  IsCommonScope:
    Fn::Equals:
    - Ref: Scope
    - common
  IsEnvScope:
    Fn::Equals:
    - Ref: Scope
    - env
  COGNITOCLIENTIDCondition:
    Fn::And:
    - Condition: IsEnvScope
    - Fn::Not:
      - Fn::Equals:
        - Ref: COGNITOCLIENTID-Value
        - none
Resources:
  COGNITOCLIENTID:
    Type: Custom::SecureSSMParameter
    Condition: COGNITOCLIENTIDCondition
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /COGNITO/CLIENT_ID
      Type: SecureString
      Value:
        Ref: COGNITOCLIENTID-Value
Outputs:
  Status:
    Value: 'Parameters created successfully for scope: ${Scope}'
  Environment:
    Condition: IsEnvScope
    Value: !Ref environment
  ParametersCreated:
    Value: Parameters processed successfully