AWSTemplateFormatVersion: '2010-09-09'
Description: Smart Parameter Store - Common and Environment-specific SSM parameters
Parameters:
  environment:
    Type: String
    AllowedValues:
    - dev
    - qa
    - stage
    - prod
    Default: dev
  Scope:
    Type: String
    AllowedValues:
    - common
    - env
    Default: env
    Description: common = deploy only common params, env = deploy only env-specific
      params
  CognitoClientIdValue:
    Type: String
    NoEcho: true
    Default: none
  CognitoUserPoolIdValue:
    Type: String
    NoEcho: true
    Default: none
  
Conditions:
  IsCommonScope:
    Fn::Equals:
    - Ref: Scope
    - common
  IsEnvScope:
    Fn::Equals:
    - Ref: Scope
    - env
  CognitoClientIdCondition:
    Fn::And:
    - Condition: IsEnvScope
    - Fn::Not:
      - Fn::Equals:
        - Ref: CognitoClientIdValue
        - none
  CognitoUserPoolIdCondition:
    Fn::And:
    - Condition: IsEnvScope
    - Fn::Not:
      - Fn::Equals:
        - Ref: CognitoUserPoolIdValue
        - none
Resources:
  CognitoClientId:
    Type: Custom::SecureSSMParameter
    Condition: CognitoClientIdCondition
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /COGNITO/CLIENT_ID
      Type: SecureString
      Value:
        Ref: CognitoClientIdValue
  CognitoUserPoolId:
    Type: Custom::SecureSSMParameter
    Condition: CognitoClientIdCondition
    Properties:
      ServiceToken: arn:aws:lambda:us-east-2:677496345545:function:ssm-parameter-manager
      Name: /COGNITO/CLIENT_ID
      Type: SecureString
      Value:
        Ref: CognitoClientIdValue
  
Outputs:
  Status:
    Value: 'Parameters created successfully for scope: ${Scope}'
  Environment:
    Condition: IsEnvScope
    Value: !Ref environment
  ParametersCreated:
    Value: Parameters processed successfully